//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CUATRG.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CUATRGEntities4 : DbContext
    {
        public CUATRGEntities4()
            : base("name=CUATRGEntities4")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<tblAlbum> tblAlbums { get; set; }
        public DbSet<tblColorMode> tblColorModes { get; set; }
        public DbSet<tblEnvironmentalCondition> tblEnvironmentalConditions { get; set; }
        public DbSet<tblFeature> tblFeatures { get; set; }
        public DbSet<tblFilter> tblFilters { get; set; }
        public DbSet<tblImage> tblImages { get; set; }
        public DbSet<tblMetaData> tblMetaDatas { get; set; }
        public DbSet<tblMetaType> tblMetaTypes { get; set; }
        public DbSet<tblProcessedImage> tblProcessedImages { get; set; }
        public DbSet<tblSensorData> tblSensorDatas { get; set; }
        public DbSet<tblSensorDataType> tblSensorDataTypes { get; set; }
    }
}
