//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CUATRG.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblColorMode
    {
        public tblColorMode()
        {
            this.tblProcessedImages = new HashSet<tblProcessedImage>();
        }
    
        public int CMD_IDPkey { get; set; }
        public string CMD_Name { get; set; }
    
        public virtual ICollection<tblProcessedImage> tblProcessedImages { get; set; }
    }
}
