//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CUATRG.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblFilter
    {
        public tblFilter()
        {
            this.tblProcessedImages = new HashSet<tblProcessedImage>();
        }
    
        public int FLT_IDPkey { get; set; }
        public string FLT_Name { get; set; }
    
        public virtual ICollection<tblProcessedImage> tblProcessedImages { get; set; }
    }
}
