//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CUATRG.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblFile
    {
        public int Id { get; set; }
        public string FileName { get; set; }
        public int Status { get; set; }
        public System.DateTime StartStamp { get; set; }
        public Nullable<System.DateTime> EndStamp { get; set; }
    }
}
