//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CUATRG.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblMetaType
    {
        public tblMetaType()
        {
            this.tblMetaDatas = new HashSet<tblMetaData>();
        }
    
        public int MTT_IDPkey { get; set; }
        public string MTT_Name { get; set; }
        public string MTT_Description { get; set; }
        public Nullable<bool> MTT_Inactive { get; set; }
    
        public virtual ICollection<tblMetaData> tblMetaDatas { get; set; }
    }
}
