//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CUATRG.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblProcessedImage
    {
        public int PIM_IDPkey { get; set; }
        public string PIM_Name { get; set; }
        public int FLT_IDFkey { get; set; }
        public int CMD_IDFkey { get; set; }
        public int IMG_IDFkey { get; set; }
        public string PIM_Path { get; set; }
    
        public virtual tblColorMode tblColorMode { get; set; }
        public virtual tblFilter tblFilter { get; set; }
        public virtual tblImage tblImage { get; set; }
    }
}
