//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CUATRG.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSensorDataType
    {
        public tblSensorDataType()
        {
            this.tblSensorDatas = new HashSet<tblSensorData>();
        }
    
        public int SDT_IDPkey { get; set; }
        public string SDT_Name { get; set; }
    
        public virtual ICollection<tblSensorData> tblSensorDatas { get; set; }
    }
}
